name: CI/CD Workflow with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Paso 3: Crear y levantar servicios con Docker Compose
      - name: Build and run Docker containers
        run: |
          docker compose up --build -d

      # Paso 4: Verificar que los contenedores están corriendo
      - name: Check running containers
        run: docker ps

      # Esperar a que MongoDB esté listo (no sé si es necesario)
      - name: Wait for MongoDB to be ready
        run: |
          until echo > /dev/tcp/localhost/27017; do
            echo "Esperando a que MongoDB esté listo...";
            sleep 2;
          done
          echo "MongoDB está listo."

      # Paso 5: Ejecutar pruebas dentro del contenedor
      - name: Run tests in Docker container
        run: |
          docker exec CarsHub_backend_container npm test

      # Paso 6: Detener y limpiar contenedores
      - name: Shut down Docker containers
        run: docker compose down
